server:
  port: ${PORT:8080}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:healthclinic-api}
    jackson:
      time-zone: America/Recife

  datasource:
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:healthclinic}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
    hibernate:
      ddl-auto: update

  flyway:
    enabled: false
    baseline-on-migrate: false

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}